/*
==================
NOVO TEMA CURSORES
==================
*/

-- CRIANDO TABELA
CREATE TABLE ALUNO(
        RA CHAR(9) PRIMARY KEY,
        NOME VARCHAR(50)
);

-- INSERINDO OS DADOS
INSERT INTO ALUNO VALUES('111222333', 'HIGOR ROCHA');
INSERT INTO ALUNO VALUES('444555666', 'KEVIN SANTOS');
INSERT INTO ALUNO VALUES('777888999', 'MARIA CLARA');

SET SERVEROUTPUT ON

-- BLOCO PL/SQL 01
DECLARE 
    CURSOR C_ALUNO IS SELECT RA, NOME FROM ALUNO;
    V_ALUNO C_ALUNO%ROWTYPE;
BEGIN
    OPEN C_ALUNO;
    LOOP
        FETCH C_ALUNO INTO V_ALUNO;
        EXIT WHEN C_ALUNO%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ALUNO: ' || V_ALUNO.NOME || ' - RA: ' || V_ALUNO.RA);
    END LOOP;
    CLOSE C_ALUNO;
END;

-- BLOCO PL/SQL 02
DECLARE
    CURSOR C_ALUNO IS SELECT RA, NOME FROM ALUNO;
BEGIN
    FOR V_ALUNO IN C_ALUNO
    LOOP
        DBMS_OUTPUT.PUT_LINE('ALUNO: ' || V_ALUNO.NOME || ' - RA: ' || V_ALUNO.RA);
    END LOOP;
END;

-- BLOCO PL/SQL 03
DECLARE
    V_RA ALUNO.RA%TYPE := 555666777;
    V_NOME ALUNO.NOME%TYPE := 'ERNESTO ESTEVES'; 
BEGIN
    UPDATE ALUNO SET NOME = V_NOME WHERE RA = V_RA;
    IF SQL%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE ('Não houve alteração');
    END IF;
    COMMIT;
END;
