/*
===============================================
Criar um bloco PL/SQL para atualizar a tabela:
- TV Smart reajuste de 5%
- Notebook reajuste em 10%
- Mouses e Canetas reajuste em 15%
===============================================
*/

CREATE TABLE PRODUTO(
    CODIGO NUMBER(4) PRIMARY KEY,
    NOME_PROD VARCHAR2(30),
    VALOR NUMBER(10,2)
);

INSERT INTO PRODUTO VALUES(2222, 'TV SMART', 20000.00);
INSERT INTO PRODUTO VALUES(3333, 'NOTEBOOK', 2500.00);
INSERT INTO PRODUTO VALUES(4444, 'CANETA', 1500.00);
INSERT INTO PRODUTO VALUES(5555, 'MOUSE', 800.00);

DESC PRODUTO;
SELECT * FROM PRODUTO;
DROP TABLE PRODUTO;

DECLARE
    CURSOR C_PROD IS 
    SELECT * FROM PRODUTO;
BEGIN
    FOR V_PROD IN C_PROD LOOP 
      CASE V_PROD.CODIGO
        WHEN '2222' THEN 
            UPDATE PRODUTO SET VALOR = VALOR + (VALOR*0.05) WHERE V_PROD.CODIGO = CODIGO;
        WHEN '3333' THEN 
            UPDATE PRODUTO SET VALOR = VALOR + (VALOR*.1) WHERE V_PROD.CODIGO = CODIGO;
        WHEN '4444' THEN 
            UPDATE PRODUTO SET VALOR = VALOR + (VALOR*0.15) WHERE V_PROD.CODIGO = CODIGO;
        WHEN '5555' THEN 
            UPDATE PRODUTO SET VALOR = VALOR + (VALOR*0.15) WHERE V_PROD.CODIGO = CODIGO;
      END CASE;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('ALTERAÇÕES CONCLUÍDAS!');
END;
SELECT * FROM PRODUTO;
