/*
====================
NOVO TEMA PROCEDURES
====================
*/

--CRIANDO UM PROCEDIMENTO
CREATE OR REPLACE PROCEDURE PROC_NOME_ALUNO (
    P_RA IN CHAR) IS
    V_NOME VARCHAR2(50);
BEGIN
    SELECT NOME INTO V_NOME FROM ALUNO
    WHERE RA = P_RA;
    DBMS_OUTPUT.PUT_LINE (V_NOME);
END PROC_NOME_ALUNO;

--EXECUTANDO O PROCEDIMENTO
EXEC PROC_NOME_ALUNO(111222333);
