-- MÉTODO CASE - EXEMPLO

SET SERVEROUTPUT ON;
DECLARE
    V_SIGLA VARCHAR2(10):= 'TBD';
    V_CURSO VARCHAR2(30);
BEGIN
    CASE V_SIGLA
    WHEN 'TADS' THEN
        V_CURSO := 'TECNOLOGIA EM ANÁLISE E DESENVOLVIMENTO DE SISTEMAS';
    WHEN 'TBD' THEN
        V_CURSO := 'TECNOLOGIA EM BANCO DE DADOS';
    WHEN 'TGTI' THEN
        V_CURSO := 'TECNOLOGIA EM GESTÃO DE TECNOLOGIA DA INFORMAÇÃO';
    WHEN 'TRC' THEN
        V_CURSO := 'TECNOLOGIA EM REDES DE COMPUTADORES';
    WHEN 'TSEG' THEN
        V_CURSO := 'TECNOLOGIA EM SEGURANÇA DA INFORMAÇÃO';
    WHEN 'TSIN' THEN
        V_CURSO := 'TECNOLOGIA EM SISTEMAS PARA INTERNET';
    ELSE
        V_CURSO := 'CURSO DESCONHECIDO';
    END CASE;
    DBMS_OUTPUT.PUT_LINE(V_SIGLA || ' – ' || V_CURSO);
END;
