-- CONTADOR DE 1 A 20
SET SERVEROUTPUT ON
DECLARE
  V_CONTADOR NUMBER(2):= 1;
  V_MSG VARCHAR2(30):= 'FIM DO LOOP';
BEGIN
 LOOP
  DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
  V_CONTADOR := V_CONTADOR + 1;
  EXIT WHEN V_CONTADOR > 20;
  END LOOP;

 DBMS_OUTPUT.PUT_LINE(V_MSG);
END;



-- CONTADOR DE 1 A 20 (CRESCENTE)
BEGIN
 FOR V_CONTADOR IN 1..20 LOOP
  DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
END LOOP;
END;

-- CONTADOR DE 1 A 20 (DECRESCENTE)
BEGIN
 FOR V_CONTADOR IN REVERSE 1..20 LOOP
  DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
END LOOP;
END;

-- CONTADOR DE 1 A 20 (PARES)
DECLARE
 V_CONTADOR NUMBER(2):= 1;
BEGIN
 WHILE V_CONTADOR <= 20 LOOP
 IF (MOD(V_CONTADOR,2) = 0) THEN
  DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
  END IF;
  V_CONTADOR := V_CONTADOR + 1;
END LOOP;
END;
