SET SERVEROUTPUT ON -- Para ativar o server

<<PRIMEIRO_PROGRAMA>> --Título
DECLARE
    V_MSG VARCHAR2(50) := 'BOA NOITE! 03/05';
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_MSG);
END PRIMEIRO_PROGRAMA;


/*
====================================================
*/

-- CRIANDO TABELA
CREATE TABLE ALUNO (
            RA CHAR(9) PRIMARY KEY,
            NOME VARCHAR2(50));
            
INSERT INTO ALUNO VALUES ('111222333', 'HIGOR ROCHA');
INSERT INTO ALUNO VALUES ('444555666', 'SAMANTA CAETANO');
INSERT INTO ALUNO VALUES ('777888999', 'GABRIELA RIBEIRO');

--PL/SQL - EXIBINDO 1°FORMA
SET SERVEROUTPUT ON
DECLARE
    V_RA CHAR(9) := '777888999';
    V_NOME VARCHAR2(50);
BEGIN
    SELECT NOME INTO V_NOME FROM ALUNO WHERE RA = V_RA;
    DBMS_OUTPUT.PUT_LINE ('O NOME DO ALUNO É: ' || V_NOME);
END;
 
--PL/SQL - EXIBINDO 2°FORMA
SET SERVEROUTPUT ON
DECLARE
    V_RA ALUNO.RA%TYPE := '777888999';
    V_NOME ALUNO.NOME%TYPE;
BEGIN
    SELECT NOME INTO V_NOME FROM ALUNO WHERE RA = V_RA;
    DBMS_OUTPUT.PUT_LINE ('O NOME DO ALUNO É: ' || V_NOME);
END;

--PL/SQL - EXIBINDO 3° FORMA
SET SERVEROUTPUT ON
DECLARE
    V_ALUNO ALUNO%ROWTYPE;
BEGIN
    V_ALUNO.RA := '777888999';
    SELECT NOME INTO V_ALUNO.NOME FROM ALUNO WHERE RA = V_ALUNO.RA;
    DBMS_OUTPUT.PUT_LINE ('O NOME DO ALUNO É: ' || V_ALUNO.NOME);
END;

--PL/SQL - INSERINDO DADOS
DECLARE
    V_RA CHAR(9) := '497375998';
    V_NOME VARCHAR2(50) := 'HIGOR R F SILVA';
BEGIN
    INSERT INTO ALUNO VALUES (V_RA, V_NOME);
END;
    
--PL/SQL - ATUALIZANDO NOME E RA
DECLARE
    V_RA CHAR(9) := '283099658';
    V_NOME VARCHAR2(50) := 'EDINA ROCHA';
BEGIN
    UPDATE ALUNO SET RA = V_RA WHERE RA = '111222333';
    UPDATE ALUNO SET NOME = V_NOME WHERE NOME = 'NOEL FERNANDES';
END;

--PL/SQL - DELETANDO SAMANTA
DECLARE
    V_RA CHAR(9) := '444555666';
BEGIN
    DELETE FROM ALUNO WHERE RA = V_RA;
END;

DESC ALUNO;
SELECT * FROM ALUNO;


/*
====================================================
*/

--ATIVIDADE 01
DECLARE
    NUM1 NUMBER(2);
    NUM2 NUMBER(2);
    RESULT NUMBER(2);
BEGIN
    NUM1 := &NUM_1;
    NUM2 := &NUM_2;
    RESULT := NUM1+NUM2;
    DBMS_OUTPUT.PUT_LINE('O VALOR DA SOMA É: ' || RESULT);
END;


--ATIVIDADE 02
DECLARE
    SALARIO_ANTIGO NUMBER(10,2);
    SALARIO_NOVO NUMBER(10,2);
    AUMENTO FLOAT;
    FUNCIONARIO VARCHAR2(30) := 'HIGOR ROCHA'; 
BEGIN
    SALARIO_ANTIGO := &SALARIO_FUNCIONARIO;
    AUMENTO := 0.25;
    SALARIO_NOVO := SALARIO_ANTIGO * (1 + AUMENTO);
    
    DBMS_OUTPUT.PUT_LINE('NOME FUNCIONÁRIO: ' || FUNCIONARIO);
    DBMS_OUTPUT.PUT_LINE('SALARIO ATUAL: R$' || SALARIO_NOVO);
END;


--ATIVIDADE 03
DECLARE
    NUM NUMBER(2);
BEGIN
    NUM := &NUM_PESQUISA;
    -- MOD RETORNA O RESTO DE UMA DIVISÃO
    IF MOD(NUM,2) = 0 THEN
        DBMS_OUTPUT.PUT_LINE('O NÚMERO ' || NUM || ' É PAR');
    ELSE
        DBMS_OUTPUT.PUT_LINE('O NÚMERO ' || NUM || ' É IMPÁR');
    END IF;
END;


--ATIVIDADE 04
DECLARE
    V_ANO NUMBER(4) := 2021;
BEGIN
    IF (MOD(V_ANO,4) = 0 AND MOD(V_ANO,100) != 0)
    OR (MOD(V_ANO,400) = 0) THEN
        DBMS_OUTPUT.PUT_LINE('O ano ' || V_ANO || ' é BISSEXTO');
    ELSE
        DBMS_OUTPUT.PUT_LINE('O ano ' || V_ANO || ' não é BISSEXTO');
    END IF;
END;


/*
====================================================
*/

CREATE TABLE NOTAS(
        ALUNO_RA CHAR(5) PRIMARY KEY,
        COD_DISC CHAR(4),
        AV1 NUMBER(4,2),
        AV2 NUMBER(4,2),
        AV3 NUMBER(4,2),
        AULAS NUMBER(2),
        FALTAS NUMBER(2));

INSERT INTO NOTAS VALUES ('12345', '3520', 9, 10, 8.5, 80, 10);
INSERT INTO NOTAS VALUES ('67890', '3520', 6, 5, 3, 80, 20);
INSERT INTO NOTAS VALUES ('54321', '3520', 6, 5.5, 5, 80, 10);
INSERT INTO NOTAS VALUES ('09876', '3520', 7, 8.5, 6.5, 80, 40);
      
DROP TABLE NOTAS;
DESC NOTAS;
SELECT * FROM NOTAS;

/*
TERMINAR NA PRÓXIMA SEMANA
*/