-- ATIVIDADE DE NOTAS
CREATE TABLE NOTAS(
            RA CHAR(9),
            COD_DISC CHAR(4) NOT NULL,
            A1 NUMBER(3,1),
            A2 NUMBER(3,1),
            A3 NUMBER(3,1),
            AULAS NUMBER(2),
            FALTAS NUMBER(2),
            CONSTRAINT NOTAS_PK PRIMARY KEY(RA)
            );
            
INSERT INTO NOTAS VALUES ('111222333','3520',9,10,8.5,80,10);
INSERT INTO NOTAS VALUES ('222333444','3520',6,5,3, 80,20);
INSERT INTO NOTAS VALUES ('333444555','3520',6,5.5,5,80,10);
INSERT INTO NOTAS VALUES ('444555666','3520',7,8.5,6.5,80,40);

SET SERVEROUTPUT ON;
DECLARE
    V_NOTAS NOTAS%ROWTYPE;
    V_MEDIA NUMBER(3,2);
BEGIN
    SELECT * INTO V_NOTAS FROM NOTAS WHERE RA = '111222333';
    
    IF(V_NOTAS.FALTAS/V_NOTAS.AULAS > 0.25) THEN 
        DBMS_OUTPUT.PUT_LINE('REPROVADO POR FALTAS');
    ELSE
        IF(V_NOTAS.A1 >= V_NOTAS.A3) AND (V_NOTAS.A2 >= V_NOTAS.A3) THEN 
        V_MEDIA := (V_NOTAS.A1 + V_NOTAS.A2)/2;
    ELSIF (V_NOTAS.A2 >= V_NOTAS.A1) THEN
        V_MEDIA := (V_NOTAS.A2+V_NOTAS.A3)/2;
    ELSE
        V_MEDIA := (V_NOTAS.A1+V_NOTAS.A3)/2;
    END IF;
    IF (V_MEDIA < 6) THEN
        DBMS_OUTPUT.PUT_LINE ('REPROVADO POR NOTA');
    ELSE
        DBMS_OUTPUT.PUT_LINE ('APROVADO');
        END IF;
    END IF;
    DBMS_OUTPUT.PUT_LINE (V_MEDIA);
END;

DESC NOTAS;
SELECT * FROM NOTAS;



-- MÉTODO CASE - EXEMPLO
SET SERVEROUTPUT ON;
DECLARE
    V_SIGLA VARCHAR2(10):= 'TBD';
    V_CURSO VARCHAR2(30);
BEGIN
    CASE V_SIGLA
    WHEN 'TADS' THEN
        V_CURSO := 'TECNOLOGIA EM ANÁLISE E DESENVOLVIMENTO DE SISTEMAS';
    WHEN 'TBD' THEN
        V_CURSO := 'TECNOLOGIA EM BANCO DE DADOS';
    WHEN 'TGTI' THEN
        V_CURSO := 'TECNOLOGIA EM GESTÃO DE TECNOLOGIA DA INFORMAÇÃO';
    WHEN 'TRC' THEN
        V_CURSO := 'TECNOLOGIA EM REDES DE COMPUTADORES';
    WHEN 'TSEG' THEN
        V_CURSO := 'TECNOLOGIA EM SEGURANÇA DA INFORMAÇÃO';
    WHEN 'TSIN' THEN
        V_CURSO := 'TECNOLOGIA EM SISTEMAS PARA INTERNET';
    ELSE
        V_CURSO := 'CURSO DESCONHECIDO';
    END CASE;
    DBMS_OUTPUT.PUT_LINE(V_SIGLA || ' – ' || V_CURSO);
END;



-- CONTADOR DE 1 A 20
SET SERVEROUTPUT ON
DECLARE
  V_CONTADOR NUMBER(2):= 1;
  V_MSG VARCHAR2(30):= 'FIM DO LOOP';
BEGIN
 LOOP
  DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
  V_CONTADOR := V_CONTADOR + 1;
  EXIT WHEN V_CONTADOR > 20;
  END LOOP;

 DBMS_OUTPUT.PUT_LINE(V_MSG);
END;



-- CONTADOR DE 1 A 20 (CRESCENTE)
BEGIN
 FOR V_CONTADOR IN 1..20 LOOP
  DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
END LOOP;
END;

-- CONTADOR DE 1 A 20 (DECRESCENTE)
BEGIN
 FOR V_CONTADOR IN REVERSE 1..20 LOOP
  DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
END LOOP;
END;

-- CONTADOR DE 1 A 20 (PARES)
DECLARE
 V_CONTADOR NUMBER(2):= 1;
BEGIN
 WHILE V_CONTADOR <= 20 LOOP
 IF (MOD(V_CONTADOR,2) = 0) THEN
  DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
  END IF;
  V_CONTADOR := V_CONTADOR + 1;
END LOOP;
END;




