/*
==================
NOVO TEMA CURSORES
==================
*/

-- CRIANDO TABELA
CREATE TABLE ALUNO(
        RA CHAR(9) PRIMARY KEY,
        NOME VARCHAR(50)
);

-- INSERINDO OS DADOS
INSERT INTO ALUNO VALUES('111222333', 'HIGOR ROCHA');
INSERT INTO ALUNO VALUES('444555666', 'KEVIN SANTOS');
INSERT INTO ALUNO VALUES('777888999', 'MARIA CLARA');

DESC ALUNO;
SELECT * FROM ALUNO;
SET SERVEROUTPUT ON

-- BLOCO PL/SQL 01
DECLARE 
    CURSOR C_ALUNO IS SELECT RA, NOME FROM ALUNO;
    V_ALUNO C_ALUNO%ROWTYPE;
BEGIN
    OPEN C_ALUNO;
    LOOP
        FETCH C_ALUNO INTO V_ALUNO;
        EXIT WHEN C_ALUNO%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ALUNO: ' || V_ALUNO.NOME || ' - RA: ' || V_ALUNO.RA);
    END LOOP;
    CLOSE C_ALUNO;
END;

-- BLOCO PL/SQL 02
DECLARE
    CURSOR C_ALUNO IS SELECT RA, NOME FROM ALUNO;
BEGIN
    FOR V_ALUNO IN C_ALUNO
    LOOP
        DBMS_OUTPUT.PUT_LINE('ALUNO: ' || V_ALUNO.NOME || ' - RA: ' || V_ALUNO.RA);
    END LOOP;
END;

-- BLOCO PL/SQL 03
DECLARE
    V_RA ALUNO.RA%TYPE := 555666777;
    V_NOME ALUNO.NOME%TYPE := 'ERNESTO ESTEVES'; 
BEGIN
    UPDATE ALUNO SET NOME = V_NOME WHERE RA = V_RA;
    IF SQL%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE ('Não houve alteração');
    END IF;
    COMMIT;
END;


/*
===============================================
Criar um bloco PL/SQL para atualizar a tabela:
- TV Smart reajuste de 5%
- Notebook reajuste em 10%
- Mouses e Canetas reajuste em 15%
===============================================
*/

CREATE TABLE PRODUTO(
    CODIGO NUMBER(4) PRIMARY KEY,
    NOME_PROD VARCHAR2(30),
    VALOR NUMBER(10,2)
);

INSERT INTO PRODUTO VALUES(2222, 'TV SMART', 20000.00);
INSERT INTO PRODUTO VALUES(3333, 'NOTEBOOK', 2500.00);
INSERT INTO PRODUTO VALUES(4444, 'CANETA', 1500.00);
INSERT INTO PRODUTO VALUES(5555, 'MOUSE', 800.00);

DESC PRODUTO;
SELECT * FROM PRODUTO;
DROP TABLE PRODUTO;

DECLARE
    CURSOR C_PROD IS 
    SELECT * FROM PRODUTO;
BEGIN
    FOR V_PROD IN C_PROD LOOP 
      CASE V_PROD.CODIGO
        WHEN '2222' THEN 
            UPDATE PRODUTO SET VALOR = VALOR + (VALOR*0.05) WHERE V_PROD.CODIGO = CODIGO;
        WHEN '3333' THEN 
            UPDATE PRODUTO SET VALOR = VALOR + (VALOR*.1) WHERE V_PROD.CODIGO = CODIGO;
        WHEN '4444' THEN 
            UPDATE PRODUTO SET VALOR = VALOR + (VALOR*0.15) WHERE V_PROD.CODIGO = CODIGO;
        WHEN '5555' THEN 
            UPDATE PRODUTO SET VALOR = VALOR + (VALOR*0.15) WHERE V_PROD.CODIGO = CODIGO;
      END CASE;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('ALTERAÇÕES CONCLUÍDAS!');
END;
SELECT * FROM PRODUTO;





/*
====================
NOVO TEMA PROCEDURES
====================
*/

--CRIANDO UM PROCEDIMENTO
CREATE OR REPLACE PROCEDURE PROC_NOME_ALUNO (
    P_RA IN CHAR) IS
    V_NOME VARCHAR2(50);
BEGIN
    SELECT NOME INTO V_NOME FROM ALUNO
    WHERE RA = P_RA;
    DBMS_OUTPUT.PUT_LINE (V_NOME);
END PROC_NOME_ALUNO;

--EXECUTANDO O PROCEDIMENTO
EXEC PROC_NOME_ALUNO(111222333);



/*
====================================================
Criar uma procedure que deverá receber o código
de um cliente e a partir deste dado imprimir o
seu nome e seu e-mail.
====================================================
*/
CREATE TABLE CLIENTE(
    CODIGO NUMBER(4) PRIMARY KEY,
    NOME VARCHAR2(30),
    EMAIL VARCHAR2(30)
);

DESC CLIENTE;
SELECT * FROM CLIENTE;
DROP TABLE CLIENTE;

INSERT INTO CLIENTE VALUES(2222, 'HIGOR ROCHA', 'HR@DA.COM.BR');
INSERT INTO CLIENTE VALUES(3333, 'SAMANTA CAETANO', 'SC@DA.COM.BR');

CREATE OR REPLACE PROCEDURE PROC_CLIENTE (
    V_CODIGO IN NUMBER) IS
    V_NOME VARCHAR2(30);
    V_EMAIL VARCHAR2(30);
BEGIN
    SELECT NOME, EMAIL INTO V_NOME, V_EMAIL FROM CLIENTE WHERE CODIGO = V_CODIGO;
    DBMS_OUTPUT.PUT_LINE ('NOME: ' || V_NOME || ' ---- EMAIL: ' || V_EMAIL);
END PROC_CLIENTE;

EXEC PROC_CLIENTE(2222);


