--CRIANDO TABELA
creat table ALUNO (RA number(10), NOME varchar(20));

--EX1 INSERINDO DADOS
BEGIN
    insert into ALUNO (RA, NOME) values (5, 'Daniel');
END;


--EX2 ALTERANDO DADOS
BEGIN
    UPDATE ALUNO SET NOME = 'ERNESTO' WHERE RA = 5;
END;


--EX3 DELETANDO TABELA
BEGIN   
    DELETE FROM ALUNO WHERE RA = 5;
END;


--EX4 PL/SQL SALARIO
DECLARE
    SALARIO_ANTIGO NUMBER(10,2);
    SALARIO_NOVO NUMBER(10,2);
BEGIN
    SALARIO_ANTIGO := &SALARIO;
    SALARIO_NOVO := SALARIO_ANTIGO + (8/100*100);
    
    DBMS_OUTPUT.PUT_LINE('Salário atual é de : ' || SALARIO_NOVO);
END;


--EX5 PL/SQL CONVERSÃO
DECLARE
    REAL NUMBER(10,2);
    DOLAR NUMBER(10,2);
    CAMBIO NUMBER(10,2);
BEGIN
    DOLAR := &DOLAR;
    CAMBIO := &CAMBIO;
    REAL := DOLAR * CAMBIO;
    
    DBMS_OUTPUT.PUT_LINE('Você tem em Reais o total de: ' || REAL);
END;


--EX6 PL/SQL ALUGUEL
DECLARE
    VALOR_ALUGUEL NUMBER(10,2);
    QTD_MORADORES NUMBER(10,2);
    VALOR_PESSOA NUMBER(10,2);
BEGIN
    VALOR_ALUGUEL := &ALUGUEL;
    QTD_MORADORES := &MORADORES;
    VALOR_PESSOA := VALOR_ALUGUEL / QTD_MORADORES;
    
    DBMS_OUTPUT.PUT_LINE('O total para cada morador é de : ' || VALOR_PESSOA);
END;


--EX7 PL/SQL PASSAGEM
DECLARE
    VALOR_PASSAGEM NUMBER(10,2);
    QTD_REGULARES NUMBER(3);
    QTD_ESPECIAIS NUMBER(3);
    FATURAMENTO NUMBER(10,2);
BEGIN
    VALOR_PASSAGEM := &VALOR_DA_PASSAGEM;
    QTD_REGULARES := &PASSAGEIROS_REGULARES;
    QTD_ESPECIAIS := &PASSAGEIROS_ESPECIAIS;
    FATURAMENTO := ((VALOR_PASSAGEM/2)*QTD_ESPECIAIS) + (VALOR_PASSAGEM * QTD_REGULARES);
    
    DBMS_OUTPUT.PUT_LINE('O Faturamento total da Companhia é de : ' || FATURAMENTO);
END;
