SET SERVEROUTPUT ON -- Para ativar o server

<<PRIMEIRO_PROGRAMA>> --Título
DECLARE
    V_MSG VARCHAR2(50) := 'BOA NOITE! 03/05';
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_MSG);
END PRIMEIRO_PROGRAMA;

-- CRIANDO TABELA
CREATE TABLE ALUNO (
            RA CHAR(9) PRIMARY KEY,
            NOME VARCHAR2(50));
            
INSERT INTO ALUNO VALUES ('111222333', 'HIGOR ROCHA');
INSERT INTO ALUNO VALUES ('444555666', 'SAMANTA CAETANO');
INSERT INTO ALUNO VALUES ('777888999', 'GABRIELA RIBEIRO');

--PL/SQL - EXIBINDO 1°FORMA
SET SERVEROUTPUT ON
DECLARE
    V_RA CHAR(9) := '777888999';
    V_NOME VARCHAR2(50);
BEGIN
    SELECT NOME INTO V_NOME FROM ALUNO WHERE RA = V_RA;
    DBMS_OUTPUT.PUT_LINE ('O NOME DO ALUNO É: ' || V_NOME);
END;
 
--PL/SQL - EXIBINDO 2°FORMA
SET SERVEROUTPUT ON
DECLARE
    V_RA ALUNO.RA%TYPE := '777888999';
    V_NOME ALUNO.NOME%TYPE;
BEGIN
    SELECT NOME INTO V_NOME FROM ALUNO WHERE RA = V_RA;
    DBMS_OUTPUT.PUT_LINE ('O NOME DO ALUNO É: ' || V_NOME);
END;

--PL/SQL - EXIBINDO 3° FORMA
SET SERVEROUTPUT ON
DECLARE
    V_ALUNO ALUNO%ROWTYPE;
BEGIN
    V_ALUNO.RA := '777888999';
    SELECT NOME INTO V_ALUNO.NOME FROM ALUNO WHERE RA = V_ALUNO.RA;
    DBMS_OUTPUT.PUT_LINE ('O NOME DO ALUNO É: ' || V_ALUNO.NOME);
END;


/*
====================================================
*/


--PL/SQL - INSERINDO DADOS
DECLARE
    V_RA CHAR(9) := '497375998';
    V_NOME VARCHAR2(50) := 'HIGOR R F SILVA';
BEGIN
    INSERT INTO ALUNO VALUES (V_RA, V_NOME);
END;
    
--PL/SQL - ATUALIZANDO NOME E RA
DECLARE
    V_RA CHAR(9) := '283099658';
    V_NOME VARCHAR2(50) := 'EDINA ROCHA';
BEGIN
    UPDATE ALUNO SET RA = V_RA WHERE RA = '111222333';
    UPDATE ALUNO SET NOME = V_NOME WHERE NOME = 'NOEL FERNANDES';
END;

--PL/SQL - DELETANDO SAMANTA
DECLARE
    V_RA CHAR(9) := '444555666';
BEGIN
    DELETE FROM ALUNO WHERE RA = V_RA;
END;

DESC ALUNO;
SELECT * FROM ALUNO;
